spring.profiles.active: ${SPRING_PROFILES_ACTIVE:dev}
spring.profiles.include: db

spring:
  output.ansi.enabled: always

socar-jpa:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:socar;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
  dialect: org.hibernate.dialect.H2Dialect
  persistence-unit: socar
  entity-package: kr.socar.salt.jpaconfig.domain.socar.domain
  ddl-auto: create

socarlog-jpa:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:socarlog;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
  dialect: org.hibernate.dialect.H2Dialect
  persistence-unit: socarlog
  entity-package: kr.socar.salt.jpaconfig.domain.socarlog.domain
  ddl-auto: create